import json
import re
from pathlib import Path
from typing import Any

import requests
import uvicorn
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel


app = FastAPI(title="TravelWise V2")
BASE_DIR = Path(__file__).resolve().parent

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "llama3.2"


class RouteRequest(BaseModel):
    start_point: str
    end_point: str


class StopDetailRequest(BaseModel):
    start_point: str
    end_point: str
    name: str
    description: str = ""
    category: str = "Travel idea"


def extract_json_object(text: str) -> dict[str, Any] | None:
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        return None

    try:
        return json.loads(match.group(0))
    except json.JSONDecodeError:
        return None


def fallback_suggestions(text: str, start_point: str, end_point: str) -> dict[str, Any]:
    clean_text = text.strip() or "The AI did not return detailed stops. Try another route."

    return {
        "route": f"{start_point} to {end_point}",
        "summary": "Here are tourist suggestions generated for your route.",
        "stops": [
            {
                "name": "AI Travel Suggestions",
                "description": clean_text,
                "why_visit": "Generated by the local LLM based on your selected route.",
                "category": "Travel idea",
            }
        ],
    }


def fallback_details(text: str, request: StopDetailRequest) -> dict[str, Any]:
    clean_text = text.strip() or request.description or "No detailed response was returned."

    return {
        "name": request.name,
        "overview": clean_text,
        "highlights": ["Explore the main attraction", "Take photos", "Enjoy the local surroundings"],
        "suggested_time": "1 to 2 hours",
        "best_for": request.category,
        "travel_tip": "Check opening hours and route conditions before leaving.",
        "mini_itinerary": [
            "Arrive and get oriented",
            "Visit the main viewpoint or attraction",
            "Leave time for photos, food, or a short walk",
        ],
    }


@app.get("/")
async def read_index():
    return FileResponse(BASE_DIR / "static" / "index.html")


@app.post("/suggest")
async def suggest_sites(request: RouteRequest):
    prompt = f"""
You are a helpful travel assistant.

The user is traveling from {request.start_point} to {request.end_point}.
Suggest 3 to 5 tourist sites located between or reasonably along the route.

Return only valid JSON in this exact shape:
{{
  "route": "{request.start_point} to {request.end_point}",
  "summary": "One short sentence summarizing the route.",
  "stops": [
    {{
      "name": "Tourist site name",
      "description": "One or two sentence description.",
      "why_visit": "Short reason to visit.",
      "category": "Museum, nature, food, historic, viewpoint, or local culture"
    }}
  ]
}}
""".strip()

    try:
        response = requests.post(
            OLLAMA_URL,
            json={
                "model": MODEL_NAME,
                "prompt": prompt,
                "stream": False,
                "format": "json",
            },
            timeout=60,
        )
        response.raise_for_status()
    except requests.exceptions.RequestException as exc:
        raise HTTPException(
            status_code=500,
            detail=f"Error connecting to Ollama. Make sure Ollama is running and the {MODEL_NAME} model is installed. Details: {exc}",
        ) from exc

    ai_text = response.json().get("response", "")
    parsed = extract_json_object(ai_text)

    if not parsed or not isinstance(parsed.get("stops"), list):
        return fallback_suggestions(ai_text, request.start_point, request.end_point)

    parsed.setdefault("route", f"{request.start_point} to {request.end_point}")
    parsed.setdefault("summary", "Here are tourist suggestions generated for your route.")

    clean_stops = []
    for stop in parsed["stops"][:5]:
        if not isinstance(stop, dict):
            continue

        name = str(stop.get("name", "")).strip()
        description = str(stop.get("description", "")).strip()
        if not name or not description:
            continue

        clean_stops.append(
            {
                "name": name,
                "description": description,
                "why_visit": str(stop.get("why_visit", "Worth a stop along the way.")).strip(),
                "category": str(stop.get("category", "Travel idea")).strip(),
            }
        )

    if not clean_stops:
        return fallback_suggestions(ai_text, request.start_point, request.end_point)

    parsed["stops"] = clean_stops
    return parsed


@app.post("/detail")
async def stop_detail(request: StopDetailRequest):
    prompt = f"""
You are a practical travel guide.

The user is traveling from {request.start_point} to {request.end_point}.
They clicked this suggested stop: {request.name}.
Known description: {request.description}
Category: {request.category}

Go deeper into this one stop. Return only valid JSON in this exact shape:
{{
  "name": "{request.name}",
  "overview": "A richer 2 to 3 sentence overview.",
  "highlights": ["Highlight 1", "Highlight 2", "Highlight 3"],
  "suggested_time": "Suggested time to spend there.",
  "best_for": "Who this stop is best for.",
  "travel_tip": "One practical travel tip.",
  "mini_itinerary": ["Step 1", "Step 2", "Step 3"]
}}
""".strip()

    try:
        response = requests.post(
            OLLAMA_URL,
            json={
                "model": MODEL_NAME,
                "prompt": prompt,
                "stream": False,
                "format": "json",
            },
            timeout=60,
        )
        response.raise_for_status()
    except requests.exceptions.RequestException as exc:
        raise HTTPException(
            status_code=500,
            detail=f"Error connecting to Ollama for stop details. Details: {exc}",
        ) from exc

    ai_text = response.json().get("response", "")
    parsed = extract_json_object(ai_text)

    if not parsed:
        return fallback_details(ai_text, request)

    parsed.setdefault("name", request.name)
    parsed.setdefault("overview", request.description or "Detailed travel information for this stop.")
    parsed.setdefault("suggested_time", "1 to 2 hours")
    parsed.setdefault("best_for", request.category)
    parsed.setdefault("travel_tip", "Check current opening hours before you go.")

    if not isinstance(parsed.get("highlights"), list):
        parsed["highlights"] = ["Main attraction", "Local atmosphere", "Photo opportunity"]

    if not isinstance(parsed.get("mini_itinerary"), list):
        parsed["mini_itinerary"] = ["Arrive", "Explore", "Continue your route"]

    parsed["highlights"] = [str(item) for item in parsed["highlights"][:5]]
    parsed["mini_itinerary"] = [str(item) for item in parsed["mini_itinerary"][:5]]
    return parsed


app.mount("/static", StaticFiles(directory=BASE_DIR / "static"), name="static")


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8001)
